listeners.tcp {
  bind = "nmq-tcp://127.0.0.1:1883"
}

listeners.ssl {
  enable = false
}

listeners.ws {
  enable = false
}

http_server {
  enable = false
}

log {
  level = warn
  to    = [console]
}