pid = /var/run/stunnel.pid
foreground = yes
debug = 7
output = /dev/stdout

[mqtts]
accept = 0.0.0.0:8883
connect = 127.0.0.1:1883
cert = /etc/nanomq/certs/broker.crt
key = /etc/nanomq/certs/broker.key
CAfile = /etc/nanomq/certs/root_ca.crt
verifyPeer = yes